### ISSUE TITLE
🐞 Bug bundle update (to 6.0.0 stuff possibly), wont allow webserver to start

### ISSUE THREAD

**Issue by weteamsteve** [weteamsteve/squadsnap#71]
Get error `undefined method `alias_method_chain'` after running command `bundle update`

Probably from using 6.0.0 library stuff.

**Comment by weteamsteve** [comment]
```	 1: from /home/weteamsteve/.rvm/gems/ruby-2.6.0/gems/devise-1.5.4/lib/devise/rails/routes.rb:2:in `<module:Routing>'
/home/weteamsteve/.rvm/gems/ruby-2.6.0/gems/devise-1.5.4/lib/devise/rails/routes.rb:14:in `<class:RouteSet>': undefined method `alias_method_chain' for ActionDispatch::Routing::RouteSet:Class (NoMethodError)
Did you mean?  alias_method
```

**Comment by weteamsteve** [comment]
Rails 6.0.0 came out today on 8-16-2019, so maybe have to wait for gems to catch up.
